services:
  - type: static_site
    name: learnix
    env: node
    buildCommand: "npm install && npm run build"
    publishDir: "./dist/learnix/browser"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: API_KEY
        sync: false
